/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMarketRouteImport } from './routes/_authenticated/market'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedConnectionsRouteImport } from './routes/_authenticated/connections'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMarketIndexRouteImport } from './routes/_authenticated/market.index'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events.index'
import { Route as AuthenticatedAmbassadorIndexRouteImport } from './routes/_authenticated/ambassador.index'
import { Route as AuthenticatedUIdRouteImport } from './routes/_authenticated/u.$id'
import { Route as AuthenticatedTagTagRouteImport } from './routes/_authenticated/tag.$tag'
import { Route as AuthenticatedSchoolSchoolIdRouteImport } from './routes/_authenticated/school.$schoolId'
import { Route as AuthenticatedRedeemCashRouteImport } from './routes/_authenticated/redeem.cash'
import { Route as AuthenticatedRedeemAirtimeRouteImport } from './routes/_authenticated/redeem.airtime'
import { Route as AuthenticatedPostIdRouteImport } from './routes/_authenticated/post.$id'
import { Route as AuthenticatedMarketNewRouteImport } from './routes/_authenticated/market.new'
import { Route as AuthenticatedEventsNewRouteImport } from './routes/_authenticated/events.new'
import { Route as AuthenticatedCommunityIdRouteImport } from './routes/_authenticated/community.$id'
import { Route as AuthenticatedAmbassadorApplyRouteImport } from './routes/_authenticated/ambassador.apply'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketRoute = AuthenticatedMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConnectionsRoute =
  AuthenticatedConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketIndexRoute =
  AuthenticatedMarketIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMarketRoute,
  } as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEventsRoute,
  } as any)
const AuthenticatedAmbassadorIndexRoute =
  AuthenticatedAmbassadorIndexRouteImport.update({
    id: '/ambassador/',
    path: '/ambassador/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUIdRoute = AuthenticatedUIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTagTagRoute = AuthenticatedTagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchoolSchoolIdRoute =
  AuthenticatedSchoolSchoolIdRouteImport.update({
    id: '/school/$schoolId',
    path: '/school/$schoolId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRedeemCashRoute = AuthenticatedRedeemCashRouteImport.update({
  id: '/redeem/cash',
  path: '/redeem/cash',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRedeemAirtimeRoute =
  AuthenticatedRedeemAirtimeRouteImport.update({
    id: '/redeem/airtime',
    path: '/redeem/airtime',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPostIdRoute = AuthenticatedPostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketNewRoute = AuthenticatedMarketNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedMarketRoute,
} as any)
const AuthenticatedEventsNewRoute = AuthenticatedEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedEventsRoute,
} as any)
const AuthenticatedCommunityIdRoute =
  AuthenticatedCommunityIdRouteImport.update({
    id: '/community/$id',
    path: '/community/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmbassadorApplyRoute =
  AuthenticatedAmbassadorApplyRouteImport.update({
    id: '/ambassador/apply',
    path: '/ambassador/apply',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/events': typeof AuthenticatedEventsRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/market': typeof AuthenticatedMarketRouteWithChildren
  '/messages': typeof AuthenticatedMessagesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/ambassador/apply': typeof AuthenticatedAmbassadorApplyRoute
  '/community/$id': typeof AuthenticatedCommunityIdRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/market/new': typeof AuthenticatedMarketNewRoute
  '/post/$id': typeof AuthenticatedPostIdRoute
  '/redeem/airtime': typeof AuthenticatedRedeemAirtimeRoute
  '/redeem/cash': typeof AuthenticatedRedeemCashRoute
  '/school/$schoolId': typeof AuthenticatedSchoolSchoolIdRoute
  '/tag/$tag': typeof AuthenticatedTagTagRoute
  '/u/$id': typeof AuthenticatedUIdRoute
  '/ambassador/': typeof AuthenticatedAmbassadorIndexRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/market/': typeof AuthenticatedMarketIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/connections': typeof AuthenticatedConnectionsRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/home': typeof AuthenticatedHomeRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/ambassador/apply': typeof AuthenticatedAmbassadorApplyRoute
  '/community/$id': typeof AuthenticatedCommunityIdRoute
  '/events/new': typeof AuthenticatedEventsNewRoute
  '/market/new': typeof AuthenticatedMarketNewRoute
  '/post/$id': typeof AuthenticatedPostIdRoute
  '/redeem/airtime': typeof AuthenticatedRedeemAirtimeRoute
  '/redeem/cash': typeof AuthenticatedRedeemCashRoute
  '/school/$schoolId': typeof AuthenticatedSchoolSchoolIdRoute
  '/tag/$tag': typeof AuthenticatedTagTagRoute
  '/u/$id': typeof AuthenticatedUIdRoute
  '/ambassador': typeof AuthenticatedAmbassadorIndexRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/market': typeof AuthenticatedMarketIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/connections': typeof AuthenticatedConnectionsRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/events': typeof AuthenticatedEventsRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/market': typeof AuthenticatedMarketRouteWithChildren
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/ambassador/apply': typeof AuthenticatedAmbassadorApplyRoute
  '/_authenticated/community/$id': typeof AuthenticatedCommunityIdRoute
  '/_authenticated/events/new': typeof AuthenticatedEventsNewRoute
  '/_authenticated/market/new': typeof AuthenticatedMarketNewRoute
  '/_authenticated/post/$id': typeof AuthenticatedPostIdRoute
  '/_authenticated/redeem/airtime': typeof AuthenticatedRedeemAirtimeRoute
  '/_authenticated/redeem/cash': typeof AuthenticatedRedeemCashRoute
  '/_authenticated/school/$schoolId': typeof AuthenticatedSchoolSchoolIdRoute
  '/_authenticated/tag/$tag': typeof AuthenticatedTagTagRoute
  '/_authenticated/u/$id': typeof AuthenticatedUIdRoute
  '/_authenticated/ambassador/': typeof AuthenticatedAmbassadorIndexRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/market/': typeof AuthenticatedMarketIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/connections'
    | '/discover'
    | '/events'
    | '/home'
    | '/leaderboard'
    | '/market'
    | '/messages'
    | '/onboarding'
    | '/settings'
    | '/wallet'
    | '/ambassador/apply'
    | '/community/$id'
    | '/events/new'
    | '/market/new'
    | '/post/$id'
    | '/redeem/airtime'
    | '/redeem/cash'
    | '/school/$schoolId'
    | '/tag/$tag'
    | '/u/$id'
    | '/ambassador/'
    | '/events/'
    | '/market/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/connections'
    | '/discover'
    | '/home'
    | '/leaderboard'
    | '/messages'
    | '/onboarding'
    | '/settings'
    | '/wallet'
    | '/ambassador/apply'
    | '/community/$id'
    | '/events/new'
    | '/market/new'
    | '/post/$id'
    | '/redeem/airtime'
    | '/redeem/cash'
    | '/school/$schoolId'
    | '/tag/$tag'
    | '/u/$id'
    | '/ambassador'
    | '/events'
    | '/market'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/connections'
    | '/_authenticated/discover'
    | '/_authenticated/events'
    | '/_authenticated/home'
    | '/_authenticated/leaderboard'
    | '/_authenticated/market'
    | '/_authenticated/messages'
    | '/_authenticated/onboarding'
    | '/_authenticated/settings'
    | '/_authenticated/wallet'
    | '/_authenticated/ambassador/apply'
    | '/_authenticated/community/$id'
    | '/_authenticated/events/new'
    | '/_authenticated/market/new'
    | '/_authenticated/post/$id'
    | '/_authenticated/redeem/airtime'
    | '/_authenticated/redeem/cash'
    | '/_authenticated/school/$schoolId'
    | '/_authenticated/tag/$tag'
    | '/_authenticated/u/$id'
    | '/_authenticated/ambassador/'
    | '/_authenticated/events/'
    | '/_authenticated/market/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market': {
      id: '/_authenticated/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof AuthenticatedMarketRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connections': {
      id: '/_authenticated/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AuthenticatedConnectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market/': {
      id: '/_authenticated/market/'
      path: '/'
      fullPath: '/market/'
      preLoaderRoute: typeof AuthenticatedMarketIndexRouteImport
      parentRoute: typeof AuthenticatedMarketRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedEventsRoute
    }
    '/_authenticated/ambassador/': {
      id: '/_authenticated/ambassador/'
      path: '/ambassador'
      fullPath: '/ambassador/'
      preLoaderRoute: typeof AuthenticatedAmbassadorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/u/$id': {
      id: '/_authenticated/u/$id'
      path: '/u/$id'
      fullPath: '/u/$id'
      preLoaderRoute: typeof AuthenticatedUIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tag/$tag': {
      id: '/_authenticated/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/tag/$tag'
      preLoaderRoute: typeof AuthenticatedTagTagRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/school/$schoolId': {
      id: '/_authenticated/school/$schoolId'
      path: '/school/$schoolId'
      fullPath: '/school/$schoolId'
      preLoaderRoute: typeof AuthenticatedSchoolSchoolIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/redeem/cash': {
      id: '/_authenticated/redeem/cash'
      path: '/redeem/cash'
      fullPath: '/redeem/cash'
      preLoaderRoute: typeof AuthenticatedRedeemCashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/redeem/airtime': {
      id: '/_authenticated/redeem/airtime'
      path: '/redeem/airtime'
      fullPath: '/redeem/airtime'
      preLoaderRoute: typeof AuthenticatedRedeemAirtimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/post/$id': {
      id: '/_authenticated/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof AuthenticatedPostIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market/new': {
      id: '/_authenticated/market/new'
      path: '/new'
      fullPath: '/market/new'
      preLoaderRoute: typeof AuthenticatedMarketNewRouteImport
      parentRoute: typeof AuthenticatedMarketRoute
    }
    '/_authenticated/events/new': {
      id: '/_authenticated/events/new'
      path: '/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AuthenticatedEventsNewRouteImport
      parentRoute: typeof AuthenticatedEventsRoute
    }
    '/_authenticated/community/$id': {
      id: '/_authenticated/community/$id'
      path: '/community/$id'
      fullPath: '/community/$id'
      preLoaderRoute: typeof AuthenticatedCommunityIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ambassador/apply': {
      id: '/_authenticated/ambassador/apply'
      path: '/ambassador/apply'
      fullPath: '/ambassador/apply'
      preLoaderRoute: typeof AuthenticatedAmbassadorApplyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedEventsRouteChildren {
  AuthenticatedEventsNewRoute: typeof AuthenticatedEventsNewRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
}

const AuthenticatedEventsRouteChildren: AuthenticatedEventsRouteChildren = {
  AuthenticatedEventsNewRoute: AuthenticatedEventsNewRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
}

const AuthenticatedEventsRouteWithChildren =
  AuthenticatedEventsRoute._addFileChildren(AuthenticatedEventsRouteChildren)

interface AuthenticatedMarketRouteChildren {
  AuthenticatedMarketNewRoute: typeof AuthenticatedMarketNewRoute
  AuthenticatedMarketIndexRoute: typeof AuthenticatedMarketIndexRoute
}

const AuthenticatedMarketRouteChildren: AuthenticatedMarketRouteChildren = {
  AuthenticatedMarketNewRoute: AuthenticatedMarketNewRoute,
  AuthenticatedMarketIndexRoute: AuthenticatedMarketIndexRoute,
}

const AuthenticatedMarketRouteWithChildren =
  AuthenticatedMarketRoute._addFileChildren(AuthenticatedMarketRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedConnectionsRoute: typeof AuthenticatedConnectionsRoute
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRouteWithChildren
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedMarketRoute: typeof AuthenticatedMarketRouteWithChildren
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedAmbassadorApplyRoute: typeof AuthenticatedAmbassadorApplyRoute
  AuthenticatedCommunityIdRoute: typeof AuthenticatedCommunityIdRoute
  AuthenticatedPostIdRoute: typeof AuthenticatedPostIdRoute
  AuthenticatedRedeemAirtimeRoute: typeof AuthenticatedRedeemAirtimeRoute
  AuthenticatedRedeemCashRoute: typeof AuthenticatedRedeemCashRoute
  AuthenticatedSchoolSchoolIdRoute: typeof AuthenticatedSchoolSchoolIdRoute
  AuthenticatedTagTagRoute: typeof AuthenticatedTagTagRoute
  AuthenticatedUIdRoute: typeof AuthenticatedUIdRoute
  AuthenticatedAmbassadorIndexRoute: typeof AuthenticatedAmbassadorIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedConnectionsRoute: AuthenticatedConnectionsRoute,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRouteWithChildren,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedMarketRoute: AuthenticatedMarketRouteWithChildren,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedAmbassadorApplyRoute: AuthenticatedAmbassadorApplyRoute,
  AuthenticatedCommunityIdRoute: AuthenticatedCommunityIdRoute,
  AuthenticatedPostIdRoute: AuthenticatedPostIdRoute,
  AuthenticatedRedeemAirtimeRoute: AuthenticatedRedeemAirtimeRoute,
  AuthenticatedRedeemCashRoute: AuthenticatedRedeemCashRoute,
  AuthenticatedSchoolSchoolIdRoute: AuthenticatedSchoolSchoolIdRoute,
  AuthenticatedTagTagRoute: AuthenticatedTagTagRoute,
  AuthenticatedUIdRoute: AuthenticatedUIdRoute,
  AuthenticatedAmbassadorIndexRoute: AuthenticatedAmbassadorIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
